[versions]
jreleaser = "1.18.0"
lombok = "1.18.38"
sugar-next-jedis-boot = "0.1.0"
sugar-next-mybatis-boot = "0.1.0"

[plugins]
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
sugar-next-jedis-boot = { group = "team.idealstate.sugar.boot", name = "sugar-next-jedis-boot", version.ref = "sugar-next-jedis-boot" }
sugar-next-mybatis-boot = { group = "team.idealstate.sugar.boot", name = "sugar-next-mybatis-boot", version.ref = "sugar-next-mybatis-boot" }
